# Generated by Django 4.2.16 on 2025-02-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cover_image',
            field=models.CharField(default='https://img1.baidu.com/it/u=2455490295,2646246733&fm=253&fmt=auto&app=120&f=JPEG?w=500&h=647', max_length=500),
            preserve_default=False,
        ),
    ]
